### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [springpartners/springpad-export#1]
In the US (at least) the copyright default is "All Rights Reserved." Would you be open to adding a license to these files?

http://choosealicense.com/ makes it easy.
http://opensource.org/ if you want some "light" reading on the topic. :smile_cat: 

Thanks!

**Comment by chuckg19** [comment]
Added.  Thank you!

**Comment by BigBlueHat** [comment]
Great choice! :+1: Thanks.

**Comment by BigBlueHat** [comment]
Oh. Also, be sure that ships with the actual exports or it won't really matter...

Sad springpad.com is closing...it was fab while it lasted.
